2025-02-04 21:31:04,266 - INFO - Python Version: 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
2025-02-04 21:31:04,266 - INFO - Platform: win32
2025-02-04 21:31:04,266 - INFO - Working Directory: C:\Users\Owner\OneDrive\Music\Documents\cloner
2025-02-04 21:31:04,266 - INFO - Starting application
2025-02-04 21:31:04,266 - DEBUG - Importing dependencies after admin check
2025-02-04 21:31:04,334 - CRITICAL - Unexpected error: cannot import name 'DiskVerifier' from 'disk_ops' (C:\Users\Owner\OneDrive\Music\Documents\cloner\disk_ops.py)

Traceback (most recent call last):
  File "C:\Users\Owner\OneDrive\Music\Documents\cloner\main.py", line 90, in main
    from gui import DiskClonerApp
  File "C:\Users\Owner\OneDrive\Music\Documents\cloner\gui.py", line 11, in <module>
    from disk_ops import (
ImportError: cannot import name 'DiskVerifier' from 'disk_ops' (C:\Users\Owner\OneDrive\Music\Documents\cloner\disk_ops.py)

